[env]
_.file = '.env'

[tools]
rust = "latest"

[tasks.start]
description = "Login user"
run = "cargo run -- login"
[tasks.projects]
alias = "p"
description = "List all projects"
run = "cargo run -- project"
