@GITLAB_TOKEN
GET https://gitlab.com/api/v4/projects
Authorization: Bearer {{GITLAB_TOKEN}}

##
@GITLAB_TOKEN
GET https://gitlab.com/api/v4/user
Authorization: Bearer {{GITLAB_TOKEN}}

##
## 
##
@GITLAB_TOKEN
GET https://gitlab.com/api/v4/users/4500276/projects
Authorization: Bearer {{GITLAB_TOKEN}}

##
## GET all projects that the authenticated user is a member of
##
@GITLAB_TOKEN
GET https://gitlab.com/api/v4/projects?membership=true
Authorization: Bearer {{GITLAB_TOKEN}}

##
@GITLAB_TOKEN
GET https://gitlab.com/api/v4/users/projects
Authorization: Bearer {{GITLAB_TOKEN}}

##
@GITLAB_TOKEN
GET https://gitlab.com/api/v4/issues?assignee_id=4500276
Authorization: Bearer {{GITLAB_TOKEN}}


##
@GITLAB_TOKEN
GET https://gitlab.com/api/v4/issues?membership=true
Authorization: Bearer {{GITLAB_TOKEN}}


##
@GITLAB_TOKEN
POST https://gitlab.com/api/v4/projects/13951944/issues
Authorization: Bearer {{GITLAB_TOKEN}}
Content-Type: application/json


{
  "title": "New issue",
  "description": "This is a new issue",
  "assignee_id": 4500276
}
